Repository bounswe/bounswe2018group10, pull requests merged in 2018-04, with the labels that each got.

#66 functions are ready, fill application.py, create template files
  twitter-api/BackStabbers/application.py
  twitter-api/BackStabbers/twitter_api.py
Labels: feature, help wanted, in progress, review

#68 backend for twitter follower app added
  twitter-api/BackStabbers/application.py
Labels: feature, help wanted, in progress, priority: high

#70 templates for twitter follower app added
  twitter-api/BackStabbers/templates/home.html
  twitter-api/BackStabbers/templates/list.html
Labels: feature, help wanted, in progress, priority: high

#71 What Happened App
  .gitignore
  twitter-api/what-happened-app/README.md
  twitter-api/what-happened-app/app.py
  twitter-api/what-happened-app/eventsapi.py
  twitter-api/what-happened-app/requirements.txt
  twitter-api/what-happened-app/static/ress.css
  twitter-api/what-happened-app/static/style.css
  twitter-api/what-happened-app/templates/_events.day.html
  twitter-api/what-happened-app/templates/_events.year.html
  twitter-api/what-happened-app/templates/_main.html
  twitter-api/what-happened-app/templates/events.html
  twitter-api/what-happened-app/templates/home.html
  twitter-api/what-happened-app/twapi.py
Labels: enhancement, feature, priority: medium

#75 [feature] added "Search Job" Twitter App Fixes #73
  twitter-api/search-job/.gitignore
  twitter-api/search-job/README.md
  twitter-api/search-job/application.py
  twitter-api/search-job/requirements.txt
  twitter-api/search-job/static/style.css
  twitter-api/search-job/templates/auth.html
  twitter-api/search-job/templates/follow.html
  twitter-api/search-job/templates/guest.html
  twitter-api/search-job/templates/home.html
  twitter-api/search-job/templates/search_job.html
Labels: feature
